### ISSUE TITLE
用这个chrome插件的同学越来越多了。

### ISSUE THREAD

**Issue by cbwang2016** [Zakelly/PKUGetClassHelper#3]

**Comment by Zakelly** [comment]
确实是一个非常棘手的问题。
只要服务器不挂就好，我了解到他们用的是单机服务器，性能并不强，最好限制频率尽量减少对服务器的压力...

另外注意保护自己，别被找去喝茶...

**Comment by cbwang2016** [comment]
嗯。感觉现在的频率限制还算比较合适的。

不过喝茶嘛，他们真想查肯定逃不了的。。。。
