### ISSUE TITLE
第一次运行时会在https://raw.githubusercontent.com/naptha/tessdata/gh-pages/3.02/eng.traineddata.gz下载9.0MB的数据包

### ISSUE THREAD

**Issue by cbwang2016** [Zakelly/PKUGetClassHelper#6]
![image](https://user-images.githubusercontent.com/18070081/46056032-5b35e200-c181-11e8-9e8d-339cd8a1ca7a.png)
5.82s
这是第一次识别验证码缓慢的主要原因

**Comment by Zakelly** [comment]
emmm，感觉这个有点无解，库的初始化API里好像没有数据包来源可以配置。。。除非去改他的库
